[project]
name = "agents"
version = "0.1.0"
description = "Python examples using Restate for agents"
requires-python = ">=3.12"

dependencies = [
    "hypercorn",
    "restate_sdk[serde]>=0.7.3",
    "pydantic>=2.10.6",
    "openai",
]