services:
  restatedev_agent:
    # Build the image from the Dockerfile in the current directory
    build: .
    ports:
      - 9081:9081
    env_file: ".env"
    environment:
        - RESTATE_HOST=http://restate:8080
    command: ["uv", "run", "agents/restatedev"]
  langgraph_agent:
    # Build the image from the Dockerfile in the current directory
    build: .
    ports:
      - 9082:9082
    env_file: ".env"
    environment:
        - RESTATE_HOST=http://restate:8080
    command: ["uv", "run", "agents/langgraph"]
  host_agent:
    # Build the image from the Dockerfile in the current directory
    build: .
    ports:
      - "9080:9080"
    env_file: ".env"
    environment:
        - RESTATE_HOST=http://restate:8080
    command: ["uv", "run", "agents/host_agent"]
  restate:
    image: restatedev/restate:latest
    ports:
      - 8080:8080
      - 9090:9090
      - 9070:9070
      - 8081:8081
    restart: "no"
    environment:
      - RESTATE_WORKER__INVOKER__INACTIVITY_TIMEOUT=10min
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535

  runtimesetup:
    image: alpine
    depends_on:
      - restate
      - restatedev_agent
      - langgraph_agent
      - host_agent
    restart: "no"
    entrypoint: [
        "sh",
        "-c",
        'sleep 5 &&
        apk add --no-cache bash jq curl &&
        curl -X POST ''restate:9070/deployments'' -H ''content-type: application/json'' -d ''{"uri": "http://host_agent:9080"}'' &&
        curl -X POST ''restate:9070/deployments'' -H ''content-type: application/json'' -d ''{"uri": "http://restatedev_agent:9081/restate/v1"}'' &&
        curl -X POST ''restate:9070/deployments'' -H ''content-type: application/json'' -d ''{"uri": "http://langgraph_agent:9082/restate/v1"}'' &&
        sleep 3 &&
        curl -X POST restate:8080/HostAgent/my-user/register_remote_agents -H ''content-type: application/json'' -d ''["http://restatedev_agent:9081", "http://langgraph_agent:9082"]'' &&
        exit 1',
      ]
