services:
  weather_agent:
    # Path to the Dockerfile from root of the project
    build:
      context: .
    ports:
      - 9081:9081
    env_file: ".env" # Your openAI key `echo "OPENAI_API_KEY=your_api_key_here" >> .env`
    environment:
        - RESTATE_HOST=http://restate:8080
    command: ["/app/.venv/bin/python", "/app/a2a/weather"]
  reimbursement_agent:
    # Path to the Dockerfile from root of the project
    build:
      context: .
    ports:
      - 9082:9082
    env_file: ".env" # Your openAI key `echo "OPENAI_API_KEY=your_api_key_here" >> .env`
    environment:
        - RESTATE_HOST=http://restate:8080
    command: ["/app/.venv/bin/python", "/app/a2a/reimbursement"]
  host_agent:
    # Path to the Dockerfile from root of the project
    build:
      context: .
    ports:
      - 9080:9080
    depends_on:
      - weather_agent
      - reimbursement_agent
    env_file: ".env" # Your openAI key `echo "OPENAI_API_KEY=your_api_key_here" >> .env`
    environment:
        - RESTATE_HOST=http://restate:8080
        - REMOTE_AGENTS=http://weather_agent:9081,http://reimbursement_agent:9082
    command: ["/app/.venv/bin/python", "/app/a2a/host_agent"]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
  restate:
    image: restatedev/restate:latest
    ports:
      - 8080:8080
      - 9090:9090
      - 9070:9070
      - 8081:8081
    restart: "no"
    environment:
      - RESTATE_WORKER__INVOKER__INACTIVITY_TIMEOUT=10min
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
  runtimesetup:
    image: alpine
    depends_on:
      - restate
      - weather_agent
      - reimbursement_agent
      - host_agent
    restart: "no"
    entrypoint: [
        "sh",
        "-c",
        'sleep 5 &&
        apk add --no-cache bash jq curl &&
        curl ''restate:9070/deployments'' --json ''{"uri": "http://host_agent:9080"}'' &&
        curl ''restate:9070/deployments'' --json ''{"uri": "http://weather_agent:9081/restate/v1"}'' &&
        curl ''restate:9070/deployments'' --json ''{"uri": "http://reimbursement_agent:9082/restate/v1"}'' &&
        exit 1',
      ]

